# LOGGING
logging:
  level:
    root: INFO
    com.netflix.config.sources: ERROR

# SPRING BOOT PROPERTIES
spring:
  # Redis.
  redis:
    # 配置格式变成了Duration类型
    timeout: 12000ms
    host: 127.0.0.1
    database: 0
    #密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    port: 6379
